### ISSUE TITLE
Remove files that should be excluded

### ISSUE THREAD

**Issue by MichaelCurrin** [gustavosabbag/gustavosabbag.github.io#8]
In a Jekyll project, some files should only exist locally and not in version control 

Delete vendor/

Delete .DS_Store

Delete _site

**Comment by MichaelCurrin** [comment]
And I recommend creating a .gitignore file like this

https://github.com/MichaelCurrin/jekyll-blog-demo/blob/master/.gitignore

**Comment by gustavosabbag** [comment]
Thank you for the nice suggestions!
